version: '2.18.1'

services:
   postgres:
      image: postgres:12
      container_name: postgres
      
      environment:
         POSTGRES_DB: DB_REFACTOR
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgresql123*_
      ports:
         - "5432:5432"
      volumes:
         - ./scripts:/docker-entrypoint-initdb.d

   spring-boot-app:
      build:
         context: ./ # Ruta al directorio que contiene el Dockerfile
      image: spring-boot-app
      container_name: spring-boot-app
      ports:
         - "8080:8080"
      depends_on:
         - postgres
      environment:
         SPRING_DATASOURCE_URL: r2dbc:postgresql://postgres:5432/DB_REFACTOR?currentSchema=ref_autenticacion
         SPRING_DATASOURCE_USERNAME: postgres
         SPRING_DATASOURCE_PASSWORD: postgresql123*_
         SPRING_JWT_SECRET_KEY: 9aaf7b6e2c692f9e3a36c9d67ec7c609d42c50b93cc14b79f8ff83536c46f31c
         SPRING_HOST_CLIENT: http://localhost:1000