
# POST http://localhost:8080/api/v1/registrar
# Content-Type: application/json

# {
#     "usuario": "usvvvvvvvv399",
#     "telefono" : "+573148487338",
#     "contrasena": "123",
#     "correo": "unigonzalez078@gmail.com"
# }


    # "telefono" : "+573146743903",

# POST http://localhost:8080/api/v1/login
# Content-Type: application/json
# Authorization: Bearer 
# {
#     "usuario": "",
#     "contrasena": ""
# }

# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1czF1c3QyMmVmc3RlcjIzMzEzMjM5OSIsImlhdCI6MTY5OTExNTQ0MSwiZXhwIjoxNjk5MjAxODQxfQ.D86f8-ciMcqm75ybG5imJ2m-G4mYlHQAmvpk-FxB0zw


POST http://localhost:8080/api/v1/recuperar
Content-Type: application/json

{
    "usuario": "usvvvvvvvv399",
    "emailOrPhone": "+573148487338",
    "isCorreo": true
}